### ISSUE TITLE
coordinates of the relative pose between two frames

### ISSUE THREAD

**Issue by AlonMendelson** [applied-ai-lab/zero-shot-pose#1]
Hi! first of all thank you for this great work and your for the effort to further annotate the co3d dataset. I'm facing an issue when computing a relative pose between 2 car frames using your gt annotations.
I'm trying to compute the relative pose between two car images, the first 351_37072_67647/00072.jpg and the second 106_12650_23736/00042.jpg. I attached their images below.
I'm following your multiplication scheme as presented in the paper and compute: R_2 x T_2 x Inv(T_1) x Inv(R_1)
with R_1, R_2 being the camera extrinsics (built from the viewpoint.R and viewpoint.T entries in co3d dataset for each frame) and T_1, T_2 your annotated transformation matrices. the relative pose that i'm getting represented as a rotation vector is (-0.02, 0.57, -1.46) which means a ~90 deg rotation, but looking at the images it feels to me that it should be a lot less as what seperates the frames in my eyes is just a slight elevation. Am I doing something wrong in my calculation? or perhaps misinterpreting this relative pose? 
another question I have in that matter is if there is a way to understand the axis (x,y,z) in coordinate frame in which this relative pose is presented. is it aligned with the axis of any of the pointclouds? are in some other way?
Thanks a lot! 
![image](https://user-images.githubusercontent.com/49724627/180448319-33141d61-8aec-4bd8-a6a3-6a985b5d661c.png)
 
![image](https://user-images.githubusercontent.com/49724627/180448552-c998d032-08b3-4eb9-992d-56bc361a0665.png)

**Comment by bibbygoodwin** [comment]
Hi Alon,

Thanks for your interest in this codebase, and I'm glad you've found the work interesting. 

You're right that the result you appear to be getting there doesn't intuitively match up with the viewpoint differences in those two images. Your multiplication scheme appears correct, however, so I suspect that there might be a bug either in the way in which you are composing these matrices, the way you are producing camera transformation matrices from viewpoint & translation, or possibly just in your conversion from a matrix result to the Euler angle representation you have shared (Euler angles, having so many different possible axis conventions, are more confusing than you might expect, and I try to avoid them!).

A simple check to rule out the last option. The matrix I get (using the same transform composition as quoted by you and in the paper) that describes the transform for these particular 2 images is:
```
tensor([[ 0.9953, -0.0196, -0.0949,  0.2694],
        [-0.0337,  0.8481, -0.5287,  5.2360],
        [ 0.0908,  0.5294,  0.8435, -2.0223],
        [ 0.0000,  0.0000,  0.0000,  1.0000]])
```
A useful function for the rotation element of this is to compute the geodesic distance (rotation angle in an axis-angle representation) represented by this matrix. Here's a simple function for this:
```python
def so3_geodesic_angle_from_matrix(R):
    return torch.acos((torch.trace(R.squeeze())-1)/2)
```
Running `so3_geodesic_angle_from_matrix(R)` on the above matrix gives me 0.5671 radians, or in degrees, a 32.49º difference. I'd say this corresponds more intuitively to what we see above.

As a second step, I'd look at the camera transformation matrices. The Pytorch3D transform format can be a little confusing, as 4x4 matrices denoting transforms are intended to post-multiply (!) the 4D homogenous coordinates they transform (take a look at the 'CONVENTIONS' section within the part of the docs that describes the pytorch3d.transforms.Transform3d class: https://pytorch3d.readthedocs.io/en/latest/modules/transforms.html#pytorch3d.transforms.Transform3d

I can see you closed the issue before I got back, so hopefully you had already resolved this. Let me know if you have any issues!
