### ISSUE TITLE
where is co3d_dataset_fix?

### ISSUE THREAD

**Issue by chenhonghua** [applied-ai-lab/zero-shot-pose#3]
Dear authors, thanks for this insightful work, which inspires me a lot!

I followed the instruction of this repo, but I cannot find co3d_dataset_fix.

I also tried to use co3d_dataset, but with the following error "name 'co3d_root' is not defined".

So, could you please give some advice?

**Comment by Cedric-Perauer** [comment]
In case if it is still needed, you can simply delete that line and use the "co3d_dataset.py" import that is already commented inside the  co3d_pose_dataset.py file
