### ISSUE TITLE
Info about "canonical" frame alignment within the same category

### ISSUE THREAD

**Issue by AlbertoRemus** [applied-ai-lab/zero-shot-pose#5]
Hi! Really great work!

I was investigating a bit the alignment transformations to bring all the point clouds to a canonical reference frame

what I discovered is that by taking the inverse of this matrices to premultiply the available point clouds https://github.com/applied-ai-lab/zero-shot-pose/tree/main/data/class_labels/car I end up in a correct alignment wrt the yellow car that's our reference in 5 cases out of 9

![Screenshot from 2023-10-20 17-10-15](https://github.com/applied-ai-lab/zero-shot-pose/assets/54797872/be9fe975-724d-4d94-8ee8-2c9363dc2810)

for the remainder 4 point clouds instead this alignment seems not happening

![Screenshot from 2023-10-20 17-10-02](https://github.com/applied-ai-lab/zero-shot-pose/assets/54797872/662a4dcc-e591-4aed-bfa7-21855c1845c0)
I present the issue with the car category but it seems happening also with others

Am I missing something ?

Thanks in advance,

Alberto

**Comment by AlbertoRemus** [comment]
It turned out the issue was a subtle big mistake on my side:

I was using CO3Dv2 instead of CO3Dv1!!

Even for the same scenes, the SfM reconstruction provides different frames (in general) for v1 and v2.

Switching to v1 produced a correct output for every considered pointcloud

![Screenshot from 2023-10-20 22-22-00](https://github.com/applied-ai-lab/zero-shot-pose/assets/54797872/d857b4ef-bcb2-4c8e-8075-f5fda58b1336)

**Comment by AlbertoRemus** [comment]
Sorry for the trouble, I hope this can be useful also in case compatibility from v1 and v2 needs to be considered in the future, I'm gonna close the issue

**Comment by bibbygoodwin** [comment]
@AlbertoRemus, thanks for raising the issue! You're right, the reference frames for some of these sequences were changed between v1 and v2. Is v1 still available to download? Glad it is if so. 

Happy to share my labelling script that I used to create the original transformers (uses Open3D and is pretty speedy - took me about 20-30 seconds per sequence.

**Comment by AlbertoRemus** [comment]
@bibbygoodwin thanks for the reply! Yes, v1 is still available for download! If you'd like to share the labelling script that would be really great!
