### ISSUE TITLE
Many bugs in co3d_dataset.py

### ISSUE THREAD

**Issue by twowwj** [applied-ai-lab/zero-shot-pose#6]
Hi,

Could you please share the original co3d_dataset_fix.py.
I am trying to reproduce the experiments as your dataset.
But too many bugs were raised one by one during the repairing process.

**Comment by bibbygoodwin** [comment]
Hi,
Sorry for omission of the `co3d_dataset_fix` file - it was a few lines of alteration. I have just updated `co3d_dataset.py` to contain these lines - see this push: https://github.com/applied-ai-lab/zero-shot-pose/commit/970f9bf9b5538cfadb266fd9577a18ee6a349c36

If you are having issues running the code, have you checked you are using v1 of CO3D? Meta released v2 in the last couple of years and this is now what the main co3d repo points to. This work uses v1 -- follow instructions on this branch to install: https://github.com/facebookresearch/co3d/tree/v1

Thanks!

**Comment by twowwj** [comment]
Thanks for your quick reply!
I am using the v2, it looks like the v1 is the right one.

**Comment by bibbygoodwin** [comment]
Great - I'll update the README to make it much more explicit that v1 is the right dataset to use. If your problems persist, feel free to re-open this.
